
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}M
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.walltime}
    --mail-user=xxx@xxx
    --mail-type=END
default-resources:
  - partition=std
  - mem_mb=1000
  - walltime="120:00:00"
  #restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 5000
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
#use-singularity: True
